name: "preprocess_cpp"
backend: "preprocess_cpp"
max_batch_size: 0

input [
  {
    name: "image_raw"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 2
  }
]
